Download:
    path:   /download-file/{id}
    controller: App\Controller\MoviesDeteilController::downloadFile
    defaults:
      _format: html
    requirements:
      _locale:  en|fr
      _format:  html|rss
      year:     \d+

Setcollector:
    path:   /setcollector
    controller: App\Controller\SetCollectorController::listView
    defaults:
      _format: html
    requirements:
      _locale:  en|fr
      _format:  html|rss
      year:     \d+

StarsList:
    path:   /showcollector/stars/{{collector}}/
    controller: App\Controller\StarsListController::listView
    defaults:
      _format: html
    requirements:
      _locale:  en|fr
      _format:  html|rss
      year:     \d+

SeriesList:
    path:   /showcollector/series/{{collector}}/
    controller: App\Controller\SeriesListController::listView
    defaults:
      _format: html
    requirements:
      _locale:  en|fr
      _format:  html|rss
      year:     \d+

SeriessPhotos:
    path:   /showcollector/seriesphoto/{{collector}}/{{id}}
    controller: App\Controller\SeriessPhotosController::detailView
    defaults:
      _format: html
    requirements:
      _locale:  en|fr
      _format:  html|rss
      year:     \d+
  
SeriesTopStars:
    path:   /showcollector/topstars/series/{{collector}}/{{id}}
    controller: App\Controller\SeriesTopStarsController::detailView
    defaults:
      _format: html
    requirements:
      _locale:  en|fr
      _format:  html|rss
      year:     \d+
  
ProducnetTopStars:
    path:   /showcollector/topstars/producent/{{collector}}/{{id}}
    controller: App\Controller\ProducnetTopStarsController::detailView
    defaults:
      _format: html
    requirements:
      _locale:  en|fr
      _format:  html|rss
      year:     \d+

SeriessBanner:
    path:   /showcollector/seriesbanners/{{collector}}/{{id}}
    controller: App\Controller\SeriessBannerController::detailView
    defaults:
      _format: html
    requirements:
      _locale:  en|fr
      _format:  html|rss
      year:     \d+

ProducentsList:
    path:   /showcollector/producents/{{collector}}/
    controller: App\Controller\ProducentsListController::listView
    defaults:
      _format: html
    requirements:
      _locale:  en|fr
      _format:  html|rss
      year:     \d+


MoviesList:
    path:   /showcollector/movies/{{collector}}/
    controller: App\Controller\MoviesListController::listView
    defaults:
      _format: html
    requirements:
      _locale:  en|fr
      _format:  html|rss
      year:     \d+

ProducentsDetail:
    path:   /showcollector/{{collector}}/producents/deteil/{{id}}/
    controller: App\Controller\ProducentsDetailController::detailView
    defaults:
      _format: html
    requirements:
      _locale:  en|fr
      _format:  html|rss
      year:     \d+

SeriesDetail:
    path:   /showcollector/{{collector}}/serie/deteil/{{id}}/
    controller: App\Controller\SeriesDetailController::detailView
    defaults:
      _format: html
    requirements:
      _locale:  en|fr
      _format:  html|rss
      year:     \d+

MoviesDeteil:
    path:   /showcollector/{{collector}}/movies/deteil/{{id}}/
    controller: App\Controller\MoviesDeteilController::detailView
    defaults:
      _format: html
    requirements:
      _locale:  en|fr
      _format:  html|rss
      year:     \d+

controllers:
    resource: ../src/Controller/
    type: attribute
